### ISSUE TITLE
Static Library

### ISSUE THREAD

**Issue by OlafvdSpek** [coapp-packages/libpng#1]
Could a static library be provided for libpng?

**Comment by madewokherd** [comment]
I think I'll wait on https://github.com/coapp-packages/zlib/issues/3 as I'll want to link to the correct static zlib (although I'm not entirely clear on how static libs are linked to their dependencies) and follow whatever convention is established.

**Comment by camsteffen** [comment]
What's the status here? I was able to statically link libpng. But then I switched to NuGet and dynamic linking is the only option?

**Comment by OlafvdSpek** [comment]
The future is https://github.com/Microsoft/vcpkg

**Comment by madewokherd** [comment]
Really, I have to package all these libraries AGAIN? Why can't they just make the nuget native stuff better?

Anyway, there are static variations of the zlib nuget package now, so I can take another look at this.

**Comment by OlafvdSpek** [comment]
I think a lot has been packaged already..
I think Nuget just isn't build to handle 'native' stuff.
