### ISSUE TITLE
add NuGet build targets for MSVC 2015 (v140)

### ISSUE THREAD

**Issue by igagis** [coapp-packages/libpng#3]
Add NuGet targets to build for MSVS 2015 tools v140 and upload new package to NuGet repository

**Comment by madewokherd** [comment]
CC @Raggles 

I'm looking into this, and we have a dependency on zlib, which we do not control. Version 1.2.8.7, which we're using now, does not support v140.

Version 1.2.8.8, the current version, supports v140, but does not support static linking.

So, options:
- Use the zlib shipped inside the libpng source tree instead. (Which works but is blargh.)
- Make another zlib that's different from the official one and depend on that. (Which potentially makes us mutually incompatible with other nuget packages using zlib.)
- Update the zlib dependency and drop support for v100, v110, and static linking.

I'm inclined to do the last one, but I'd like to put it up for discussion first, if there's anyone around who cares.

**Comment by Raggles** [comment]
Yea, I built my own zlib package for testing libpng which had all the flavors (https://www.myget.org/gallery/raggles), but I'm inclined to agree with you, I think we should rely on the official zlib and if people really want the other options they will have to build it themselves.  Or we could nicely ask whoever controls the zlib package to add static overlays.

**Comment by igagis** [comment]
I don't care about v100 and v110 support, so last one looks best, as for me :). Static linking is not really that necessary also.

**Comment by igagis** [comment]
By the way, is there really a need to divide by compiler? AFAIK in C and C++ there is a binary backwards compatibility between standards. I.e. the library built by C++'99 compiler can be used by code built by C++'11 compiler, isn't it? If we remove this division by v100, v110, v140 altogether then the problem will not arise again when v150 comes out?

I.e. have targets listed like this:
[x86,release] { 
//..
}

[x86,debug] { 
//...
}

[x64,release] { 
//...
}

[x64,debug] { 
//...
}

**Comment by Raggles** [comment]
http://siomsystems.com/mixing-visual-studio-versions/

**Comment by madewokherd** [comment]
It might be worth checking into whether ucrtbase solves these problems, though that won't really help without dropping v120.

**Comment by madewokherd** [comment]
New version uploaded: https://www.nuget.org/packages/libpng/1.5.10.13

**Comment by igagis** [comment]
Thanks! Will try it out in the evening...

**Comment by igagis** [comment]
It works. Closing the issue.
